import type { DatasetSpecification } from '../types/schema';

/**
 * Export dataset specification as formatted JSON
 */
export function exportAsJSON(spec: DatasetSpecification): string {
  return JSON.stringify(spec, null, 2);
}

/**
 * Export dataset specification as Markdown
 */
export function exportAsMarkdown(spec: DatasetSpecification): string {
  const lines: string[] = [];

  // Header
  lines.push(`# LoRA Training Dataset Specification`);
  lines.push(``);
  lines.push(`**SREF Code:** \`${spec.sref_code}\``);
  lines.push(``);

  // Style Analysis
  lines.push(`## Style Analysis`);
  lines.push(``);
  lines.push(`### Primary Style`);
  lines.push(`${spec.style_analysis.primary_style}`);
  lines.push(``);

  lines.push(`### Era Influence`);
  lines.push(`${spec.style_analysis.era_influence}`);
  lines.push(``);

  lines.push(`### Color Palette`);
  spec.style_analysis.color_palette.forEach(color => {
    lines.push(`- ${color}`);
  });
  lines.push(``);

  lines.push(`### Key Characteristics`);
  spec.style_analysis.key_characteristics.forEach(char => {
    lines.push(`- ${char}`);
  });
  lines.push(``);

  lines.push(`### Best Subjects`);
  spec.style_analysis.best_subjects.forEach(subject => {
    lines.push(`- ${subject}`);
  });
  lines.push(``);

  lines.push(`### Avoid Subjects`);
  spec.style_analysis.avoid_subjects.forEach(subject => {
    lines.push(`- ${subject}`);
  });
  lines.push(``);

  // Training Recommendations
  lines.push(`## Training Recommendations`);
  lines.push(``);
  lines.push(`**Recommended Dataset Size:** ${spec.training_recommendations.recommended_dataset_size} images`);
  lines.push(``);

  lines.push(`### Subject Distribution`);
  Object.entries(spec.training_recommendations.optimal_subject_distribution).forEach(([category, percentage]) => {
    lines.push(`- **${category}:** ${percentage}%`);
  });
  lines.push(``);

  // Permutation Batches
  lines.push(`## Permutation Batches`);
  lines.push(``);

  const priorityOrder = { high: 1, medium: 2, low: 3 };
  const sortedBatches = [...spec.permutation_batches].sort((a, b) => {
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });

  sortedBatches.forEach(batch => {
    const priorityEmoji = batch.priority === 'high' ? '⭐' : batch.priority === 'medium' ? '🔸' : '◽';

    lines.push(`### ${priorityEmoji} Batch ${batch.batch_number}: ${batch.batch_name}`);
    lines.push(``);
    lines.push(`- **Category:** ${batch.category}`);
    lines.push(`- **Priority:** ${batch.priority}`);
    lines.push(`- **Image Count:** ${batch.image_count}`);
    lines.push(``);

    lines.push(`**Prompt:**`);
    lines.push(`\`\`\``);
    lines.push(batch.prompt);
    lines.push(`\`\`\``);
    lines.push(``);

    if (batch.notes) {
      lines.push(`**Notes:** ${batch.notes}`);
      lines.push(``);
    }
  });

  // Prompt Guidelines
  lines.push(`## Prompt Guidelines`);
  lines.push(``);

  if (spec.prompt_guidelines.keep_simple) {
    lines.push(`**Keep Prompts Simple:** Yes - let the SREF handle styling`);
    lines.push(``);
  }

  lines.push(`### Avoid These Style Keywords`);
  spec.prompt_guidelines.avoid_style_keywords.forEach(keyword => {
    lines.push(`- \`${keyword}\``);
  });
  lines.push(``);

  lines.push(`### Recommended Additions`);
  spec.prompt_guidelines.recommended_additions.forEach(addition => {
    lines.push(`- ${addition}`);
  });
  lines.push(``);

  // Footer
  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by LoRA Training Dataset Generator*`);

  return lines.join('\n');
}

/**
 * Download file with given content
 */
export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
